// Generated by github.com/liuhan907/waka/protoc/protoc-gen-cellnet
// Source: waka.proto
// DO NOT EDIT!!!

using CellnetSDK.Meta;

namespace WakaProto
{
    /// <summary>
    /// waka.proto 元数据提供者
    /// </summary>
    public class WakaProtoMetaProvider
    {
        /// <summary>
        /// 注册消息
        /// </summary>
        static public void RegisterAll()
        {
            
            MetaTable.RegisterMessageMeta("WakaProto.Heart", 4267541978, new WakaProto.Heart().GetType(), (d) => WakaProto.Heart.Parser.ParseFrom(d));
            
            MetaTable.RegisterMessageMeta("WakaProto.Transport", 2220271715, new WakaProto.Transport().GetType(), (d) => WakaProto.Transport.Parser.ParseFrom(d));
            
            MetaTable.RegisterMessageMeta("WakaProto.FutureRequest", 3011786867, new WakaProto.FutureRequest().GetType(), (d) => WakaProto.FutureRequest.Parser.ParseFrom(d));
            
            MetaTable.RegisterMessageMeta("WakaProto.FutureResponse", 1912887258, new WakaProto.FutureResponse().GetType(), (d) => WakaProto.FutureResponse.Parser.ParseFrom(d));
            
        }
    }
}
